version: "3.7"

services:
  krakend-api-gateway:
    container_name: krakend
    image: devopsfaith/krakend
    ports:
      - 8081:8080
    volumes:
      - ./infra/krakend-config:/etc/krakend/
    command: run --config /etc/krakend/krakend.json

  express-backend:
    container_name: express
    build:
      context: "."
    ports:
      - "3001:3001"
