org: jonasgirdzijauskas
app: sample-test
service: sample-test
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  - ${file(./hello/hello.yml)}
  - ${file(./greeting/greeting.yml)}